#!/bin/bash

echo "[PRE-COMMIT] Info: Starting linting process..."

cd ../server
# currently does nothing

cd ../frontend
pnpm run lint && prettier --write

echo "[PRE-COMMIT] Info: Completed linting process."

exit 0
