const EnumValues = {
  AirportType: {
    INTERNATIONAL: { label: "International", value: "INTERNATIONAL" },
    REGIONAL: { label: "Regional", value: "REGIONAL" },
    DOMESTIC: { label: "Domestic", value: "DOMESTIC" },
  },
  CertificationIssuer: {
    FAA: { label: "Federal Aviation Administration", value: "FAA" },
    EASA: { label: "European Union Aviation Safety Agency", value: "EASA" },
    CAA: { label: "Civil Aviation Authority", value: "CAA" },
    TRANSPORT_CANADA: { label: "Transport Canada", value: "TRANSPORT_CANADA" },
    DGCA: { label: "Directorate General of Civil Aviation", value: "DGCA" },
    CAAC: { label: "Civil Aviation Administration of China", value: "CAAC" },
    CASA: { label: "Civil Aviation Safety Authority", value: "CASA" },
    ICAO: { label: "International Civil Aviation Organization", value: "ICAO" },
    ANAC: { label: "Agência Nacional de Aviação Civil", value: "ANAC" },
    GCAA: { label: "General Civil Aviation Authority", value: "GCAA" },
    SACAA: { label: "South African Civil Aviation Authority", value: "SACAA" },
    BOEING: { label: "Boeing", value: "BOEING" },
    AIRBUS: { label: "Airbus", value: "AIRBUS" },
    CESSNA: { label: "Cessna", value: "CESSNA" },
    EMBRAER: { label: "Embraer", value: "EMBRAER" },
    BOMBARDIER: { label: "Bombardier", value: "BOMBARDIER" },
    DASSAULT: { label: "Dassault Aviation", value: "DASSAULT" },
    GULFSTREAM: { label: "Gulfstream", value: "GULFSTREAM" },
    IATA: { label: "International Air Transport Association", value: "IATA" },
    RED_CROSS: { label: "Red Cross", value: "RED_CROSS" },
    AHA: { label: "American Heart Association", value: "AHA" },
    FLIGHT_SAFETY: { label: "FlightSafety International", value: "FLIGHT_SAFETY" },
    CAE: { label: "CAE", value: "CAE" },
  },
  CertificationIssuingCountry: {
    US: { label: "United States", value: "US" },
    EU: { label: "European Union", value: "EU" },
    CANADA: { label: "Canada", value: "CANADA" },
    INDIA: { label: "India", value: "INDIA" },
    CHINA: { label: "China", value: "CHINA" },
    AUSTRALIA: { label: "Australia", value: "AUSTRALIA" },
    UAE: { label: "United Arab Emirates", value: "UAE" },
    GLOBAL: { label: "Global", value: "GLOBAL" },
  },
  CrewAvailability: {
    AVAILABLE: { label: "Available", value: "AVAILABLE" },
    ON_DUTY: { label: "On-Duty", value: "ON_DUTY" },
    ON_LEAVE: { label: "On-Leave", value: "ON_LEAVE" },
    UNAVAILABLE: { label: "Unavailable", value: "UNAVAILABLE" },
  },
  CrewRole: {
    CAPTAIN: { label: "Captain", value: "CAPTAIN" },
    FIRST_OFFICER: { label: "First Officer", value: "FIRST_OFFICER" },
    SECOND_OFFICER: { label: "Seconds Officer", value: "SECOND_OFFICER" },
    THIRD_OFFICER: { label: "Third Officer", value: "THIRD_OFFICER" },
    RELIEF_CREW_MEMBER: { label: "Relief Crew Member", value: "RELIEF_CREW_MEMBER" },
    FLIGHT_ENGINEER: { label: "Flight Engineer", value: "FLIGHT_ENGINEER" },
    AIRBORNE_SENSOR_OPR: { label: "Airborne Sensor Opr.", value: "AIRBORNE_SENSOR_OPR" },
    PURSER: { label: "Purser", value: "PURSER" },
    FLIGHT_ATTENDANT: { label: "Flight Attendant", value: "FLIGHT_ATTENDANT" },
    FLIGHT_MEDIC: { label: "Flight Medic", value: "FLIGHT_MEDIC" },
    LOADMASTER: { label: "Loadmaster", value: "LOADMASTER" },
  },
  PlaneAvailability: {
    AVAILABLE: { label: "Available", value: "AVAILABLE" },
    UNDER_MAINTENANCE: { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
    IN_USE: { label: "In-Use", value: "IN_USE" },
    RETIRED: { label: "Retired", value: "RETIRED" },
  },
  RunwaySurfaceType: {
    ASPHALT: { label: "Asphalt", value: "ASPHALT" },
    CONCRETE: { label: "Concrete", value: "CONCRETE" },
    GRASS: { label: "Grass", value: "GRASS" },
    GRAVEL: { label: "Gravel", value: "GRAVEL" },
    DIRT: { label: "Dirt", value: "DIRT" },
    COMP_MATERIAL: { label: "Composite Materials", value: "COMP_MATERIAL" },
  },
  GroundVehicleAvailability: {
    AVAILABLE: { label: "Available", value: "AVAILABLE" },
    IN_USE: { label: "In-Use", value: "IN_USE" },
    UNDER_MAINTENANCE: { label: "Under-Maintenance", value: "UNDER_MAINTENANCE" },
    OUT_OF_SERVICE: { label: "Out-Of-Service", value: "OUT_OF_SERVICE" },
  },
  GroundVehicleType: {
    TUG: { label: "Tug", value: "TUG" },
    REFUELER: { label: "Refueler", value: "REFUELER" },
    LOADER: { label: "Loader", value: "LOADER" },
    CATERING: { label: "Catering", value: "CATERING" },
    DE_ICER: { label: "De-Icer", value: "DE_ICER" },
    PUSHBACK: { label: "Pushback", value: "PUSHBACK" },
    BUS: { label: "Bus", value: "BUS" },
  },
};
export default EnumValues;
